using UnityEngine;

public class KeyPickup : MonoBehaviour
{
    public GameObject uiKeyDisplay;  // Iを取得したときに表示するUI
    public GameObject enemySet;      // I取得後に出Fさせる

    void OnTriggerEnter(Collider other)
    {
        // プレイヤ`が触れた龊悉韦叻
        if (other.CompareTag("Player"))
        {
            // 偿互氓趣虺霈Fさせる
            if (enemySet != null)
            {
                enemySet.SetActive(true);
            }

            // プレイヤ`にIを持たせる
            other.GetComponent<PlayerInventory>().hasKey = true;

            // UI表示（例：画面にIアイコンを表示）
            uiKeyDisplay.SetActive(true);

            // このオブジェクト（I）を削除
            Destroy(gameObject);
        }
    }
}
