using UnityEngine;

public class KnifePickup : MonoBehaviour
{
    public string weaponName = "Knife";     // 武器の名前（武器管理に登hする用）
    public int slotIndex = 0;               // 武器スロット番号
    public GameObject weaponUI;             // 武器UI（例：画面表示）
    public GameObject enemySet;             // ナイフ取得後に出Fさせる偿互氓

    void OnTriggerEnter(Collider other)
    {
        // プレイヤ`が接触したか_J
        if (other.CompareTag("Player"))
        {
            weaponUI.SetActive(true); // 武器UIを表示

            // WeaponManagerのインスタンスを探す
            WeaponManager weaponManager = FindFirstObjectByType<WeaponManager>();
            if (weaponManager != null)
            {
                // 武器を登h
                weaponManager.PickupWeapon(weaponName, slotIndex);

                // 长虺霈Fさせる
                if (enemySet != null)
                {
                    enemySet.SetActive(true);
                }

                // このオブジェクトを削除
                Destroy(gameObject);

                // メッセ`ジ表示と抗音
                MessageManager.Instance.ShowPickupMessage("Picked up a knife");
                MessageManager.Instance.PlayPickupSound();

                // UI
                UIManager.Instance.ShowCombatTutorial(true);


            }
        }
    }
}
